version: '3.5'

services:
  # api
  api01:
    container_name: api01
    hostname: api01
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: 'postgresql://postgres:password@localhost:5432/postgres?schema=public'
      JWT_SECRET: 'e7a58dde987f60c533eed313c3b567f50db9beb890599e244b68b8ba3ed4d68f'
    # ports:
    #   - '3001:3001'
    network_mode: host
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '0.5G'
        # reservations:
        #   cpus: '0.25'
        #   memory: 256M

  # postgres
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    command: postgres -c 'max_connections=450'
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
    # ports:
    #   - '5432:5432'
    network_mode: host
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '8G'

  # nginx
  nginx:
    container_name: viphouse-backend-nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api01
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.2GB'
